// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: protos/protobuf/soup/SoupMessage.proto

package soup

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 查询大厅房间数据
type RoomHallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoomHallReq) Reset() {
	*x = RoomHallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomHallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomHallReq) ProtoMessage() {}

func (x *RoomHallReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomHallReq.ProtoReflect.Descriptor instead.
func (*RoomHallReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{0}
}

type RoomHallRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*RoomHallRes_RoomRes `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *RoomHallRes) Reset() {
	*x = RoomHallRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomHallRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomHallRes) ProtoMessage() {}

func (x *RoomHallRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomHallRes.ProtoReflect.Descriptor instead.
func (*RoomHallRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{1}
}

func (x *RoomHallRes) GetRooms() []*RoomHallRes_RoomRes {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 创建房间
type CreateRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Max      uint32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateRoomReq) Reset() {
	*x = CreateRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReq) ProtoMessage() {}

func (x *CreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReq.ProtoReflect.Descriptor instead.
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateRoomReq) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *CreateRoomReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateRoomRes) Reset() {
	*x = CreateRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRes) ProtoMessage() {}

func (x *CreateRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRes.ProtoReflect.Descriptor instead.
func (*CreateRoomRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 加入房间
type JoinRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatsChange []*RoomMemberSeatRes `protobuf:"bytes,1,rep,name=seatsChange,proto3" json:"seatsChange,omitempty"`
}

func (x *JoinRoomRes) Reset() {
	*x = JoinRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRes) ProtoMessage() {}

func (x *JoinRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRes.ProtoReflect.Descriptor instead.
func (*JoinRoomRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomRes) GetSeatsChange() []*RoomMemberSeatRes {
	if x != nil {
		return x.SeatsChange
	}
	return nil
}

// 离开房间
type LeaveRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveRoomReq) Reset() {
	*x = LeaveRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReq) ProtoMessage() {}

func (x *LeaveRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReq.ProtoReflect.Descriptor instead.
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{6}
}

type LeaveRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveRoomRes) Reset() {
	*x = LeaveRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRes) ProtoMessage() {}

func (x *LeaveRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRes.ProtoReflect.Descriptor instead.
func (*LeaveRoomRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{7}
}

// 准备
type PrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrepareReq) Reset() {
	*x = PrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReq) ProtoMessage() {}

func (x *PrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReq.ProtoReflect.Descriptor instead.
func (*PrepareReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{8}
}

type PrepareRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrepareRes) Reset() {
	*x = PrepareRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRes) ProtoMessage() {}

func (x *PrepareRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRes.ProtoReflect.Descriptor instead.
func (*PrepareRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{9}
}

// 踢人
type KickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aid   string `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *KickReq) Reset() {
	*x = KickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickReq) ProtoMessage() {}

func (x *KickReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickReq.ProtoReflect.Descriptor instead.
func (*KickReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{10}
}

func (x *KickReq) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *KickReq) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type KickRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KickRes) Reset() {
	*x = KickRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRes) ProtoMessage() {}

func (x *KickRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRes.ProtoReflect.Descriptor instead.
func (*KickRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{11}
}

// 换位置
type ExchangeSeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ExchangeSeatReq) Reset() {
	*x = ExchangeSeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeSeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSeatReq) ProtoMessage() {}

func (x *ExchangeSeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSeatReq.ProtoReflect.Descriptor instead.
func (*ExchangeSeatReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{12}
}

func (x *ExchangeSeatReq) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ExchangeSeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExchangeSeatRes) Reset() {
	*x = ExchangeSeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeSeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSeatRes) ProtoMessage() {}

func (x *ExchangeSeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSeatRes.ProtoReflect.Descriptor instead.
func (*ExchangeSeatRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{13}
}

// 聊天或者提问
type ChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{14}
}

func (x *ChatReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds uint64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
}

func (x *ChatRes) Reset() {
	*x = ChatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRes) ProtoMessage() {}

func (x *ChatRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRes.ProtoReflect.Descriptor instead.
func (*ChatRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{15}
}

func (x *ChatRes) GetSeconds() uint64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

// MC 选择回答
type AnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Answer uint32 `protobuf:"varint,2,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *AnswerReq) Reset() {
	*x = AnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerReq) ProtoMessage() {}

func (x *AnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerReq.ProtoReflect.Descriptor instead.
func (*AnswerReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{16}
}

func (x *AnswerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnswerReq) GetAnswer() uint32 {
	if x != nil {
		return x.Answer
	}
	return 0
}

type AnswerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AnswerRes) Reset() {
	*x = AnswerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRes) ProtoMessage() {}

func (x *AnswerRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRes.ProtoReflect.Descriptor instead.
func (*AnswerRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{17}
}

// 结束游戏
type EndReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndReq) Reset() {
	*x = EndReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndReq) ProtoMessage() {}

func (x *EndReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndReq.ProtoReflect.Descriptor instead.
func (*EndReq) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{18}
}

type EndRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *EndRes) Reset() {
	*x = EndRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRes) ProtoMessage() {}

func (x *EndRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRes.ProtoReflect.Descriptor instead.
func (*EndRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{19}
}

func (x *EndRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 大厅推送消息
type HallPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HallPush) Reset() {
	*x = HallPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HallPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallPush) ProtoMessage() {}

func (x *HallPush) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallPush.ProtoReflect.Descriptor instead.
func (*HallPush) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{20}
}

// 房间推送消息
type RoomPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatsChange []*RoomMemberSeatRes `protobuf:"bytes,1,rep,name=seatsChange,proto3" json:"seatsChange,omitempty"`
}

func (x *RoomPush) Reset() {
	*x = RoomPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPush) ProtoMessage() {}

func (x *RoomPush) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPush.ProtoReflect.Descriptor instead.
func (*RoomPush) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{21}
}

func (x *RoomPush) GetSeatsChange() []*RoomMemberSeatRes {
	if x != nil {
		return x.SeatsChange
	}
	return nil
}

// 房间成员信息
type RoomMemberSeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aid     string `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	AvaName string `protobuf:"bytes,2,opt,name=avaName,proto3" json:"avaName,omitempty"`
	AvaHead string `protobuf:"bytes,3,opt,name=avaHead,proto3" json:"avaHead,omitempty"`
	Index   uint32 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Owner   bool   `protobuf:"varint,5,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *RoomMemberSeatRes) Reset() {
	*x = RoomMemberSeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMemberSeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMemberSeatRes) ProtoMessage() {}

func (x *RoomMemberSeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMemberSeatRes.ProtoReflect.Descriptor instead.
func (*RoomMemberSeatRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{22}
}

func (x *RoomMemberSeatRes) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *RoomMemberSeatRes) GetAvaName() string {
	if x != nil {
		return x.AvaName
	}
	return ""
}

func (x *RoomMemberSeatRes) GetAvaHead() string {
	if x != nil {
		return x.AvaHead
	}
	return ""
}

func (x *RoomMemberSeatRes) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RoomMemberSeatRes) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type RoomHallRes_RoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RoomHallRes_RoomRes) Reset() {
	*x = RoomHallRes_RoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomHallRes_RoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomHallRes_RoomRes) ProtoMessage() {}

func (x *RoomHallRes_RoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_protobuf_soup_SoupMessage_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomHallRes_RoomRes.ProtoReflect.Descriptor instead.
func (*RoomHallRes_RoomRes) Descriptor() ([]byte, []int) {
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RoomHallRes_RoomRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomHallRes_RoomRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protos_protobuf_soup_SoupMessage_proto protoreflect.FileDescriptor

var file_protos_protobuf_soup_SoupMessage_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x73, 0x6f, 0x75, 0x70, 0x2f, 0x53, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d,
	0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x68, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x48,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x52, 0x05, 0x72, 0x6f, 0x6f,
	0x6d, 0x73, 0x1a, 0x2d, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x51, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0b,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x73,
	0x65, 0x61, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x52, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x22,
	0x0c, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x22, 0x31, 0x0a,
	0x07, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x09, 0x0a, 0x07, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x0f, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x11, 0x0a, 0x0f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x07,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x22, 0x33, 0x0a, 0x09, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x22, 0x08, 0x0a, 0x06, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x22, 0x22, 0x0a,
	0x06, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x0a, 0x0a, 0x08, 0x48, 0x61, 0x6c, 0x6c, 0x50, 0x75, 0x73, 0x68, 0x22, 0x40, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x75, 0x73, 0x68, 0x12, 0x34, 0x0a, 0x0b, 0x73, 0x65, 0x61,
	0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x52, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22,
	0x85, 0x01, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x76, 0x61, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x76, 0x61, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x76, 0x61, 0x48, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x76, 0x61, 0x48, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x6f, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_protobuf_soup_SoupMessage_proto_rawDescOnce sync.Once
	file_protos_protobuf_soup_SoupMessage_proto_rawDescData = file_protos_protobuf_soup_SoupMessage_proto_rawDesc
)

func file_protos_protobuf_soup_SoupMessage_proto_rawDescGZIP() []byte {
	file_protos_protobuf_soup_SoupMessage_proto_rawDescOnce.Do(func() {
		file_protos_protobuf_soup_SoupMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_protobuf_soup_SoupMessage_proto_rawDescData)
	})
	return file_protos_protobuf_soup_SoupMessage_proto_rawDescData
}

var file_protos_protobuf_soup_SoupMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_protos_protobuf_soup_SoupMessage_proto_goTypes = []interface{}{
	(*RoomHallReq)(nil),         // 0: RoomHallReq
	(*RoomHallRes)(nil),         // 1: RoomHallRes
	(*CreateRoomReq)(nil),       // 2: CreateRoomReq
	(*CreateRoomRes)(nil),       // 3: CreateRoomRes
	(*JoinRoomReq)(nil),         // 4: JoinRoomReq
	(*JoinRoomRes)(nil),         // 5: JoinRoomRes
	(*LeaveRoomReq)(nil),        // 6: LeaveRoomReq
	(*LeaveRoomRes)(nil),        // 7: LeaveRoomRes
	(*PrepareReq)(nil),          // 8: PrepareReq
	(*PrepareRes)(nil),          // 9: PrepareRes
	(*KickReq)(nil),             // 10: KickReq
	(*KickRes)(nil),             // 11: KickRes
	(*ExchangeSeatReq)(nil),     // 12: ExchangeSeatReq
	(*ExchangeSeatRes)(nil),     // 13: ExchangeSeatRes
	(*ChatReq)(nil),             // 14: ChatReq
	(*ChatRes)(nil),             // 15: ChatRes
	(*AnswerReq)(nil),           // 16: AnswerReq
	(*AnswerRes)(nil),           // 17: AnswerRes
	(*EndReq)(nil),              // 18: EndReq
	(*EndRes)(nil),              // 19: EndRes
	(*HallPush)(nil),            // 20: HallPush
	(*RoomPush)(nil),            // 21: RoomPush
	(*RoomMemberSeatRes)(nil),   // 22: RoomMemberSeatRes
	(*RoomHallRes_RoomRes)(nil), // 23: RoomHallRes.RoomRes
}
var file_protos_protobuf_soup_SoupMessage_proto_depIdxs = []int32{
	23, // 0: RoomHallRes.rooms:type_name -> RoomHallRes.RoomRes
	22, // 1: JoinRoomRes.seatsChange:type_name -> RoomMemberSeatRes
	22, // 2: RoomPush.seatsChange:type_name -> RoomMemberSeatRes
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_protobuf_soup_SoupMessage_proto_init() }
func file_protos_protobuf_soup_SoupMessage_proto_init() {
	if File_protos_protobuf_soup_SoupMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomHallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomHallRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeSeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeSeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HallPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomMemberSeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_protobuf_soup_SoupMessage_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomHallRes_RoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_protobuf_soup_SoupMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_protobuf_soup_SoupMessage_proto_goTypes,
		DependencyIndexes: file_protos_protobuf_soup_SoupMessage_proto_depIdxs,
		MessageInfos:      file_protos_protobuf_soup_SoupMessage_proto_msgTypes,
	}.Build()
	File_protos_protobuf_soup_SoupMessage_proto = out.File
	file_protos_protobuf_soup_SoupMessage_proto_rawDesc = nil
	file_protos_protobuf_soup_SoupMessage_proto_goTypes = nil
	file_protos_protobuf_soup_SoupMessage_proto_depIdxs = nil
}
